### ISSUE TITLE
Nothing happens.

### ISSUE THREAD

**Issue by vrmuza** [dibrale/ceruleus#29]
I'm from yesterday's thread. I'm not a programmer.

I saw your most recent change concerning the Touch button and pulled and still nothing happening when I send a message in ooba webui. There's nothing in the console windows to go off of or anything.

Things to mention:

- I'm on windows.
- When installing requirements.txt for squire I get

```
ERROR: Cannot install geojson==3.0.1 and pyowm==3.3.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested geojson==3.0.1
    pyowm 3.3.0 depends on geojson<3 and >=2.3.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) C:\Textgen\ceruleus\squire>
```

- ooba now saves characters in yaml format and not the old json but in my testing I used an older .json character
- In the {char}_persistent.json files in the ooba /logs folder there's a thing that says `"visible": [` which used to be called `"data_visible": [` in the past before it got changed
- I saw in modules/stringutils.py line 116 there's `json_convo_list = convo['data_visible']` if that means anything
- the out.txt file in squire_output/out.txt always stays at 0kb

If there's any other info I can add I'd be glad to give it

**Comment by vrmuza** [comment]
Logs. The only way I can get more console output is by putting some random text into squire_output/out.txt and then i get the second console log

<details>
<summary>Log from main.py</summary>

```
(venv) C:\Textgen\ceruleus>main.py
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/judge_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/aye_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/nay_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/body_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/character_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/continue_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/goal_eval_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/goal_thought_eval_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/set_goal_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/statement_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/summarize_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found templates/synthesize_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found C:/Textgen/oobabooga_windows/text-generation-webui/characters/Sakura.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Found work/thoughts.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Found work/goals.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Found results/goals_met.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Found results/goals_failed.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Found work/answers.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Found results/thoughts.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Found results/goals.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Found results/answers.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Found C:/Textgen/oobabooga_windows/text-generation-webui/logs/Sakura_persistent.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Found squire/squire.py
[ceruleus] Friday, July 07, 2023, 20:37:21: Found squire/template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found squire/keyword_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found squire/question.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Found model.bin
[ceruleus] Friday, July 07, 2023, 20:37:21: Found 27/27 input files
C:\Textgen\ceruleus\main.py:338: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
C:\Textgen\ceruleus\main.py:339: DeprecationWarning: There is no current event loop
  asyncio.ensure_future(main())
[ceruleus] Friday, July 07, 2023, 20:37:21: Initializing the work files
[ceruleus] Friday, July 07, 2023, 20:37:21: Writing work/answers.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Writing work/thoughts.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Writing work/goals.json
[ceruleus] Friday, July 07, 2023, 20:37:21: Wrote work/answers.json as JSON
[ceruleus] Friday, July 07, 2023, 20:37:21: Writing squire/question.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Wrote work/thoughts.json as JSON
[ceruleus] Friday, July 07, 2023, 20:37:21: Wrote work/goals.json as JSON
[ceruleus] Friday, July 07, 2023, 20:37:21: Wrote squire/question.txt as text file
[ceruleus] Friday, July 07, 2023, 20:37:21: Loading templates/statement_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Loading templates/body_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Loading templates/character_template.txt
[ceruleus] Friday, July 07, 2023, 20:37:21: Loaded templates/statement_template.txt as text file
[ceruleus] Friday, July 07, 2023, 20:37:21: Loaded templates/body_template.txt as text file
[ceruleus] Friday, July 07, 2023, 20:37:21: Loaded templates/character_template.txt as text file
[ceruleus] Friday, July 07, 2023, 20:37:21: Initializing Llama model
llama.cpp: loading model from model.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1800
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 9031.70 MB (+ 1608.00 MB per state)
.
llama_init_from_file: kv self size  = 1406.25 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
[ceruleus] Friday, July 07, 2023, 20:37:21: Monitoring squire_output directory
[ceruleus] Friday, July 07, 2023, 20:37:21: Starting server at localhost:1230
[ceruleus] Friday, July 07, 2023, 20:37:22: Waiting at semaphore for pause:True
[ceruleus] Friday, July 07, 2023, 20:37:33: Received {'query': 'id'} from websocket
[ceruleus] Friday, July 07, 2023, 20:37:33: Got request from queue: {'query': 'id'}
[ceruleus] Friday, July 07, 2023, 20:37:33: Queued reply to send: {'script_name': 'ceruleus'}
[ceruleus] Friday, July 07, 2023, 20:37:33: Sending {'script_name': 'ceruleus'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:34: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:36: Received {'query': 'id'} from websocket
[ceruleus] Friday, July 07, 2023, 20:37:36: Got request from queue: {'query': 'id'}
[ceruleus] Friday, July 07, 2023, 20:37:36: Queued reply to send: {'script_name': 'ceruleus'}
[ceruleus] Friday, July 07, 2023, 20:37:36: Sending {'script_name': 'ceruleus'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:36: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:37: Received {'query': 'semaphore'} from websocket
[ceruleus] Friday, July 07, 2023, 20:37:37: Got request from queue: {'query': 'semaphore'}
[ceruleus] Friday, July 07, 2023, 20:37:37: Queued reply to send: {'pause': False, 'webui': True, 'squire': True}
[ceruleus] Friday, July 07, 2023, 20:37:37: Sending {'pause': False, 'webui': True, 'squire': True} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:38: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:40: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:42: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:44: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:46: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:48: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:51: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:53: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:55: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:57: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:37:59: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:38:01: Sending {'waiting': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:38:02: Received {'pause': True} from websocket
[ceruleus] Friday, July 07, 2023, 20:38:02: Got request from queue: {'pause': True}
[ceruleus] Friday, July 07, 2023, 20:38:02: Queued reply to send: {'pause': True}
[ceruleus] Friday, July 07, 2023, 20:38:02: Sending {'pause': True} to websocket
[ceruleus] Friday, July 07, 2023, 20:38:02: Semaphore cleared with pause:True
[ceruleus] Friday, July 07, 2023, 20:38:02: Sending {'going': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:38:02: Loading C:/Textgen/oobabooga_windows/text-generation-webui/logs/Sakura_persistent.json
[ceruleus] Friday, July 07, 2023, 20:38:02: Loaded C:/Textgen/oobabooga_windows/text-generation-webui/logs/Sakura_persistent.json as JSON
[ceruleus] Friday, July 07, 2023, 20:38:02: Loading work/thoughts.json
[ceruleus] Friday, July 07, 2023, 20:38:02: Loading work/answers.json
[ceruleus] Friday, July 07, 2023, 20:38:02: Loaded work/thoughts.json as JSON
[ceruleus] Friday, July 07, 2023, 20:38:02: Loaded work/answers.json as JSON
[ceruleus] Friday, July 07, 2023, 20:38:02: received 1000 (OK); then sent 1000 (OK)

```

</details>


<details>
<summary>After editing out.txt</summary>

```
[ceruleus] Friday, July 07, 2023, 20:40:07: Text file modified: squire_output\out.txt
[ceruleus] Friday, July 07, 2023, 20:40:07: Additional event detected, but suppressed: squire_output\out.txt
[ceruleus] Friday, July 07, 2023, 20:40:07: Time since prior event: 0 ms
[ceruleus] Friday, July 07, 2023, 20:40:07: Sending {'id': 'squire_listener', 'status': 'event', 'timestamp': 1688776807.588699} to websocket
[ceruleus] Friday, July 07, 2023, 20:40:07: Loading squire_output\out.txt
[ceruleus] Friday, July 07, 2023, 20:40:07: Loaded squire_output\out.txt as text file
[ceruleus] Friday, July 07, 2023, 20:40:07: Semaphore cleared with pause:True
[ceruleus] Friday, July 07, 2023, 20:40:07: Semaphore cleared with pause:True
[ceruleus] Friday, July 07, 2023, 20:40:07: Aggregator waiting for text
[ceruleus] Friday, July 07, 2023, 20:40:07: Aggregator found new output
[ceruleus] Friday, July 07, 2023, 20:40:07: Loading work/answers.json
[ceruleus] Friday, July 07, 2023, 20:40:07: Preparing list of previous answers
[ceruleus] Friday, July 07, 2023, 20:40:07: Preparing thought list
[ceruleus] Friday, July 07, 2023, 20:40:07: Getting last statement from user
[ceruleus] Friday, July 07, 2023, 20:40:07: Preparing conversation data
[ceruleus] Friday, July 07, 2023, 20:40:07: Loaded work/answers.json as JSON
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at C:\Textgen\ceruleus\main.py:219> exception=KeyError('data_visible')>
Traceback (most recent call last):
  File "C:\Textgen\ceruleus\main.py", line 271, in main
    prompt = await aggregate_task
  File "C:\Textgen\ceruleus\main.py", line 46, in aggregate_text
    answer_text, thought_text, statement_text, convo_text = await asyncio.gather(
  File "C:\Textgen\ceruleus\modules\stringutils.py", line 116, in last_statement_thought
    json_convo_list = convo['data_visible']
KeyError: 'data_visible'
[ceruleus] Friday, July 07, 2023, 20:40:07: Writing work/answers.json
[ceruleus] Friday, July 07, 2023, 20:40:07: Wrote work/answers.json as JSON
[ceruleus] Friday, July 07, 2023, 20:40:07: Loading results/answers.json
[ceruleus] Friday, July 07, 2023, 20:40:07: Loaded results/answers.json as JSON
[ceruleus] Friday, July 07, 2023, 20:40:07: Writing results/answers.json
[ceruleus] Friday, July 07, 2023, 20:40:07: Wrote results/answers.json as JSON
[ceruleus] Friday, July 07, 2023, 20:40:08: Sending {'going': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:40:08: Sending {'going': 'pause'} to websocket
[ceruleus] Friday, July 07, 2023, 20:40:08: Sending {'id': 'aggregate_text', 'status': 'event', 'timestamp': 1688776807.757921} to websocket

```

</details>

**Comment by dibrale** [comment]
Hello @vrmuza,

Thank you for the detailed report, and for trying out the software! I agree with your suspicion about the new log format causing issues. Which commit of ooba are you using, if you happen to know? The file `out.txt` being empty at the beginning is normal. I will look at the issue with the log - as well as better solutions for starting the script on Windows - over the next couple of days.

**Comment by vrmuza** [comment]
ff45317

Will be watching patiently

**Comment by dibrale** [comment]
I pushed a commit that should fix the issue with nothing happening after you touch off the script. Please let me know if the new code works for you. In the meantime, I'll work on the initialization step. Using the touch command to kick off execution was useful in earlier versions of the script, but it is a superfluous step that I should get rid of at this point in the project.

Edit: For the time being, I introduced a change that should make the 'Touch' button work on Windows. Please let me know if the change fixes it for you.

**Comment by vrmuza** [comment]
The button works for me now and I got it to output something into ooba!


 When I first clicked the Touch button it I got `KeyError: 'your_name'` in console so I edited the old character.json to include `"your_name":"Anon",` after the `char_name` part at the start of the file.

<details>
<summary>Full KeyError: 'your_name' log</summary>

```
[ceruleus] Saturday, July 08, 2023, 18:30:31: Text file modified: squire_output\out.txt
[ceruleus] Saturday, July 08, 2023, 18:30:31: Loaded squire_output\out.txt
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at C:\Textgen\ceruleus\main.py:219> exception=KeyError('your_name')>
Traceback (most recent call last):
  File "C:\Textgen\ceruleus\main.py", line 271, in main
    prompt = await aggregate_task
  File "C:\Textgen\ceruleus\main.py", line 46, in aggregate_text
    answer_text, thought_text, statement_text, convo_text = await asyncio.gather(
  File "C:\Textgen\ceruleus\modules\stringutils.py", line 125, in last_statement_thought
    thought = template.format(user=attributes['your_name'], statement=statement)
KeyError: 'your_name'
[ceruleus] Saturday, July 08, 2023, 18:30:31: Loaded work/answers.json
[ceruleus] Saturday, July 08, 2023, 18:30:31: Wrote work/answers.json
[ceruleus] Saturday, July 08, 2023, 18:30:31: Loaded results/answers.json
[ceruleus] Saturday, July 08, 2023, 18:30:31: Wrote results/answers.json
```
</details>

Ceruleus/Squire model: wizardlm-7b-v1.0-uncensored.ggmlv3.q5_1.bin

After adding the `"your_name":"Anon",` to the .json, restarting everything, and pressing the Touch button, it started running with various errors in the console such as `Could not parse output, Attempts remaining:` and `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 49: invalid start byte`

The main.py console window stopped displaying new lines after the errors, though I saw CPU usage and power acting as though Ceruleus was still running its model in the background multiple times.



After resetting everything and trying again, it did manage to complete a "cycle" and output something to ooba after an F5 in the browser, with errors. 

I clicked Touch again and Ceruleus outputted a second message to ooba, although with more errors such as `context?WARNING:root:Error in on_tool_end callback: 'charmap' codec can't encode character '\u02c8' in position 140: character maps to <undefined>`, before the console log froze once more with a `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 190: invalid start byte` Ceruleus once again was still doing something with its model in the background.

[full long main.py log.txt](https://github.com/dibrale/ceruleus/files/11992603/full.long.main.py.log.txt)
[ooba log.txt](https://github.com/dibrale/ceruleus/files/11992604/ooba.log.txt)

Messages generated by Ceruleus:
![ceruleus msgs](https://github.com/dibrale/ceruleus/assets/134181330/773a6f7d-74b5-4398-bfba-6564c7281c4e)

**Comment by dibrale** [comment]
Thank you again for the detailed description. I'm glad to see that you got output! It's likely that you can tweak the prompt templates to get speech that is less 'helpful assistant' and more Mona. However, let's look at the new bugs you've found:

- Code does not account for variations in character formats, or for potentially missing fields. I can probably fix that up soon
- `Could not parse output, Attempts remaining:` is actually part of normal operation within Squire. This message is printed when the output produced by the LLM powering the script is malformed. Since you're using a 7b model (though arguably one of the better ones, and with higher-fidelity quantization), expect to see this message a lot.
- I'm going to go through the log to track down the `UnicodeDecodeError` and `context?WARNING:root:Error` instances. I will post when I have more insight into the cause of these.

**Comment by dibrale** [comment]
I pushed a commit that *should* handle the Unicode errors you have been seeing. I think the issue had something to do with standard output coming from Windows command line, but things should be working now. 

Please let me know if the issue is resolved, and whether you encounter any additional errors. I will be working on updating the software to work with more character formats next.

**Update:** YAML characters should work properly now. Please let me know if there are still any issues with these.

**Comment by vrmuza** [comment]
I did play around with the prompt .txt files with some interesting results but wiped and performed a clean install for testing the latest commit.

I got the following errors when loading a YAML character and its associated _persistent.json. I am running the same ooba commit ver as I was before - ff45317.

First a `KeyError: 'greeting'` so I added a greeting and then got a `KeyError: 'world_scenario'`. I tried making a fresh chat character to be sure and got the same `world_scenario` error.
<details>
<summary>Error 1: KeyError: 'greeting'</summary>

```
(venv) C:\Textgen\ceruleus>main.py
Traceback (most recent call last):
  File "C:\Textgen\ceruleus\main.py", line 5, in <module>
    from modules.logutils import *
  File "C:\Textgen\ceruleus\modules\logutils.py", line 5, in <module>
    from modules.config import params
  File "C:\Textgen\ceruleus\modules\config.py", line 32, in <module>
    attributes['char_greeting'] = attributes['greeting']
KeyError: 'greeting'

(venv) C:\Textgen\ceruleus>
```
</details>

<details>
<summary>Error 2: KeyError: 'world_scenario'</summary>

```
[ceruleus] Friday, July 14, 2023, 06:12:54: Loaded C:/Textgen/oobabooga_windows/text-generation-webui/logs/Magnolia_ceru_persistent.json
[ceruleus] Friday, July 14, 2023, 06:12:54: received 1000 (OK); then sent 1000 (OK)
[ceruleus] Friday, July 14, 2023, 06:13:08: Text file modified: squire_output\out.txt
[ceruleus] Friday, July 14, 2023, 06:13:08: Loaded squire_output\out.txt
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at C:\Textgen\ceruleus\main.py:219> exception=KeyError('world_scenario')>
Traceback (most recent call last):
  File "C:\Textgen\ceruleus\main.py", line 271, in main
    prompt = await aggregate_task
  File "C:\Textgen\ceruleus\main.py", line 36, in aggregate_text
    scenario=attributes['world_scenario'].strip(),
KeyError: 'world_scenario'
[ceruleus] Friday, July 14, 2023, 06:13:08: Loaded work/answers.json
[ceruleus] Friday, July 14, 2023, 06:13:08: Wrote work/answers.json
[ceruleus] Friday, July 14, 2023, 06:13:08: Loaded results/answers.json
[ceruleus] Friday, July 14, 2023, 06:13:08: Wrote results/answers.json
```

</details>

After adding a world_scenario field in the character YAML, restarting both scripts, and getting Ceruleus to start its cycle, I got a `ModuleNotFoundError: No module named 'duckduckgo_search'` and a `UnicodeEncodeError: 'charmap' codec can't encode character '\u2205' in position 2011: character maps to <undefined>`. 

I saw that it output some lines into ooba chat but when I F5'd a second time, the chat log in ooba webui was empty. Something appears to have eaten the {char}_persistent.json as it is was turned into a 0kb file. 

Full log:
[full main.py log2.txt](https://github.com/dibrale/ceruleus/files/12061105/full.main.py.log2.txt)

**Comment by dibrale** [comment]
I've added fixes for the key errors you identified. 

Regarding the `ModuleNotFoundError`, did you remember to install the dependencies for Squire when you reinstalled? The *requirements.txt* file for it stipulates `duckduckgo-search==3.6.0`, which might fix the issue. Please let me know if the issue continues despite dependencies having been installed.

As for the persistent file, it got eaten because of another text encoding error related to Windows command line. I now explicitly specify a utf-8 encoding when saving files, which should prevent this in the future.

Thank you for reporting these bugs! I don't have a good Windows test setup for most of Ceruleus, and your level of detail is very helpful.

**Comment by vrmuza** [comment]
The `ModuleNotFoundError` was dependencies.

Because of the `ERROR: Cannot install geojson==3.0.1 and pyowm==3.3.0` dependency conflict error encountered during my first installation, I had modified Squire's requirements.txt to change the requested geojson version to `geojson==2.5.0` to make the `pip install -r squire/requirements.txt` command go through. 

I redid the change to Squire's requirements.txt for this new install, re-ran the pip install, and I no longer received the dependency error.

I made a new character again but upon starting Ceruleus and Touching the file, I once again got a `KeyError: 'world_scenario'`

```future: <Task finished name='Task-1' coro=<main() done, defined at C:\Textgen\ceruleus\main.py:219> exception=KeyError('world_scenario')>
Traceback (most recent call last):
  File "C:\Textgen\ceruleus\main.py", line 271, in main
    prompt = await aggregate_task
  File "C:\Textgen\ceruleus\main.py", line 36, in aggregate_text
    scenario=attributes['world_scenario'].strip(),
KeyError: 'world_scenario'
```

Looking at the changes, would line 56 of `ceruleus\modules\config.py` be the culprit? `your_name` -> `world_scenario`

```
54	# Handle missing world_scenario
55	if 'world_scenario' not in attributes:
56          attributes['your_name'] = ''
```

**Comment by dibrale** [comment]
Thank you - I fixed the typo in *config.py*.

**Comment by dibrale** [comment]
Since there don't seem to be any new bugs crawling out of the woodwork at present, I am marking this thread closed. Thank you again for bringing these issues to my attention, and please do not hesitate to reach out if you discover any more.
